--- #YAML:1.0
name:               Helios-Panoptes
version:            1.51_4740
abstract:           Web administration interface to Helios distributed job processing system
author:
    - Andrew Johnson <lajandy at cpan dotcom>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Application:     4.06
    CGI::Application::Plugin::DBH:  4
    CGI::Fast:            1.07
    DBD::Mock:            0.11
    Helios:               2.6
    HTML::Template:       2.91
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
